### ISSUE TITLE
gmock issues prevent successful build 

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-realtime-tools#1]
I can't build this with upstream sources, only the ros-gbp version. There are other reports of the issue of not finding `gmock`.
- [report at catkin](https://github.com/ros/catkin/issues/1030)
- [report at realtime_tools](https://github.com/ros-controls/realtime_tools/issues/44)
- [reported fix](https://github.com/ros/catkin/pull/1022) for some (not working for me)

I think the patch on the last bullet has potential, but think it required adapting to arch's dir structure, perhaps. Note some of the paths added by that patch in #1022 in [this comment](https://github.com/ros/catkin/issues/1030#issuecomment-531822840). Note in the next comment what arch has sitting around with respect to gmock/gtest.

**Comment by acxz** [comment]
So here is the ArchLinux bug report: [link](https://bugs.archlinux.org/task/63793?string=gmock&project=5&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=)

I found the upstream of pkgbuilds for anthraxx, who maintains `gmock/gtest`: https://github.com/anthraxx/arch-pkgbuilds and submitted an issue for updating gmock/gtest: https://github.com/anthraxx/arch-pkgbuilds/issues/30. I also submitted a PR for upgrading the package itself: https://github.com/anthraxx/arch-pkgbuilds/pull/31

Upgrading gmock/gtest prob wont solve this issue, so someone will still have to resolve this issue, but atleast I found the repo so if anyone wants to fix this issue, they can submit PRs, instead of just complaining on bug report. I may get around to do it, but can't promise anything esp since I am not using this package.

EDIT: Well since I updated the package I thought I might as well just fix the bug, here is the PR for it, https://github.com/anthraxx/arch-pkgbuilds/pull/33

We need to keep in mind that unnecessary upstream issues get closed. @jwhendy can you take care of this? I think you can go ahead and close them now since we know it is not upstream ros problems but ArchLinux packaging.

**Comment by jwhendy** [comment]
Report at catkin was closed today (thanks for that). I was hoping someone could explain the CMakeLists related error, which was still not clear in my mind, and still isn't. I modified one from Ubuntu and one from gtest, but got a warning for every package when doing `catkin build`, so I wasn't sure. Anyway, probably arch's issue anyway.

I already closed realtime_tools 9 days ago. Are there any others to close?

Edit: and thanks for the PR! I saw this linked this morning when I commented, but assumed it was anthraxx who finally got to this since my but report has been open now since freaking Sept 2019! On one hand, hopefully this lowers the barrier to get it fixed, on the other... dang, I hope someone is at the wheel and even paying attention!?

**Comment by acxz** [comment]
I think we got all the issues covered.

Yeah, sure np thought I would actually dig into the issue and squash it. Not gonna blame antraxx though since he recently got promoted to Project Lead of Arch Linux, so he is definteily a busy man. Just glad that he has a repo for his pkgbuilds so it makes it easier to contribute to.

**Comment by acxz** [comment]
I kinda want to close this issue, since the `gtest-py3` package from the AUR has the fixes needed. But if you want to keep this open for tracedown until the upstream PR gets merged, feel free to keep it open.

Actually let's keep this issue open, I may still be having the same problem. :(

**Comment by jwhendy** [comment]
But do we depend on `gtest-py3` or will our packages pull in `gtest`? I'm assuming the latter, in which case while we might know to workaround with `gtest-py3`, others will run into this anyway. 

So, I'd propose:
- wait until the issue is actually resolved (just like we leave any other issues open that rely on upstream fixes), **edit: or**:
- redefine this org to depend on gtest-py3. That said, when official gtest is fixed... will we keep gtest-py3 or switch back?

**Comment by acxz** [comment]
We had a similar issue with libpgm a long time back, the solution then was to just let users know that `libpgm` will not work and to install `libpgm-git` unless upstream gets the fix out. We can do the same, 

Also just did a thorough check and the real-time tools is still not building for me. If you can take a look into this with the newer gtest-py3 package that would be great. Your analysis earlier really helped me understand and submit the patch for gtest.

**Comment by ristle** [comment]
If you have this issue you can delete this code from CMakeLists.txt if with enabling the gmock and gtest. Also, I deleted gmock and gtest using -Rdd for checking the result. Using the comments, I delete As a final aside, I remembered that I did this without success.

```
if(CATKIN_TOPLEVEL)
    message(STATUS "gtest not found, C++ tests can not be built. Please install the gtest headers globally in your system or checkout gtest (by running 'git clone  https://github.com/google/googletest.git -b release-1.8.0' in the source space '${CMAKE_SOURCE_DIR}' of your workspace) to enable gtests")
  else()
Is there a reason this is only proposed for gtest vs. also being a workaround if gmock is not found?
```
 Thank u)

**Comment by acxz** [comment]
Upstream issue, that just skips the tests if GMOCK is not found. https://github.com/ros-controls/realtime_tools/pull/55

**Comment by acxz** [comment]
@bionade24 can we get this package updated, ASAP? It is currently causing ros-melodic-desktop-full to fail.

**Comment by bionade24** [comment]
Done

**Comment by acxz** [comment]
The issue is still out there so I think we should keep it open, the patch is just to not compile the tests so that the rest of the ros-melodic stack can be successfully installed.

**Comment by bionade24** [comment]
Yeah, sorry forgot about this convention.
